### ISSUE TITLE
AttributeError: module 'six.moves' has no attribute 'collections_abc'

### ISSUE THREAD

**Issue by charliepascoe** [cedadev/c3s_434_ecde_page_text#26]
I'm trying to parse the updated google doc but I'm seeing the following error when I run gdoc_parser.py
`(base) RSMCP01:c3s_434_ecde_page_text clp73$ python code/gdoc_parser.py
Traceback (most recent call last):
  File "code/gdoc_parser.py", line 165, in <module>
    parse_google_spreadsheet()
  File "code/gdoc_parser.py", line 141, in parse_google_spreadsheet
    service = discovery.build('sheets', 'v4', http=http, discoveryServiceUrl=discoveryUrl)
  File "/Users/clp73/anaconda3/lib/python3.7/site-packages/googleapiclient/_helpers.py", line 134, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/Users/clp73/anaconda3/lib/python3.7/site-packages/googleapiclient/discovery.py", line 288, in build
    adc_key_path=adc_key_path,
  File "/Users/clp73/anaconda3/lib/python3.7/site-packages/googleapiclient/_helpers.py", line 134, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/Users/clp73/anaconda3/lib/python3.7/site-packages/googleapiclient/discovery.py", line 466, in build_from_document
    if isinstance(client_options, six.moves.collections_abc.Mapping):
AttributeError: module 'six.moves' has no attribute 'collections_abc'`

**Comment by charliepascoe** [comment]
So I did 
`pip install -U -r requirements.txt`  to update the requirements.
And ran the gdoc_parser again but got an error telling me that the google-api-python-client was using an incompatible version of six.
So I updated six with `pip install -U six`
And now I can run gdoc_parser without complaint.
